var fs = require('fs');
var Nightmare = require('nightmare');
var nightmare = Nightmare({
   show: true
 });

// Create a json object to populate
let a = {
	"product_name": "" ,
        "brand": "" ,
        "source_url": "",
        "mfg_color": "",
        "identifier": "",
        "meta": [
            {
                "foo": " bar bar bar "
            },
            {
                "foo2": " bar bar bar "
            }
        ],
        "videos": {
            "street_videos": [],
            "shop_videos": []
        },
        "images": {
            "shop_images" : [],
            "street_images" : []
        },

       "specific_category": "blouses_shirts" // generated by category API call

    }

nightmare
  .goto('https://www.urbanoutfitters.com/shop/champion-reverse-weave-hoodie-sweatshirt')
  .evaluate(function () {
    a.product = document.querySelector(".c-product-image  has-zoom js-zoom-product-image");
    return;
  })
  .end()
  .then((data) => {
    a.product = data;
  })
  .catch(function (error) {
    console.error('Search failed:', error);
  });

fs.writeFileSync('./Champion.json', json=a);
