// Grab modules that are required for page access
const fs = require('fs');
const Promise = require('bluebird');
const Nightmare = require('nightmare');
var nightmare = Nightmare({
   show: true,
 });

// Create a json object to populate
nightmare.goto('https://www.urbanoutfitters.com/shop/champion-reverse-weave-hoodie-sweatshirt')
      let json = {
          "product_name": "" ,
          "brand": "",
          "source_url": "",
          "mfg_color": "",
          "identifier": "",
          "meta": [
              {
                  "foo": ""
              },
              {
                  "foo2": ""
              }
          ],
          "videos": {
              "street_videos": [],
              "shop_videos": []
          },
          "images": {
              "shop_images" : [
              ],
              "street_images" : []
          },

         "specific_category": "" // generated by category API call
       }

    //Access the source_url field to update model
    .evaluate(function(){
        let x = document.querySelector('meta[property="og:url"]').content;
        return x;
      })
      .then(function(data){
        json.source_url = data;
      })
      .catch(function(err) {
        console.error(err);
      })
    });

    //Access the product_name element
    .evaluate(function(){
      let a = document.querySelector('.c-product-meta__h1 u-small--show' > span).content;
      return a;
    })
    .then(function(data){
      json.brand = data;
    })
    .catch(function(err){
      console.error(err);
    })

    //Access the images color
    .evaluate(function(){
      let a = document.querySelector('.o-list-swatches__swatch').title;
      return a;
    })
    .then(function(data){
      model.mfg_color = data;
    })
    .catch(function(err){
      console.error(err);
    })

    //Access the brand
    .evaluate(function(){
      let a = document.querySelector('.c-logo__a > img').alt;
      return a;
    })
    .then(function(data){
      model.brand = data;
    })
    .catch(function(err){
      console.error(err);
    })

    //Access all of the shop images
    .evaluate(function(){
      let b [];
      let a = document.querySelectorAll('.o-carousel__flex-wrapper > img')
      a.forEach(element){
        a.split('.');
        b.push(element)
      }
    })
    .then(function(data){
      model.image.shop_images = data[i];
    })
    .catch(function(err){
      console.error(err);
    })

    //Access all street_images
    .evaluate(function(){
      let b [];
      let a = document.querySelectorAll('.o-carousel__flex-wrapper > img')

      //Trim the data images;
      for (var i = 0; i < a.length; i++){
        a[i] = a[i].split('.').length - 1;
        b.push(a[i]);
      }
      console.log(b)
    })
    .then(function(data){
      model.image.street_images = data[i];
    })
    .catch(function(err){
      console.error(err);
    })

    model.identifier = md5()
